name: dependabot-auto-merge-workflow
on:
  pull_request:
    types: [opened]
jobs:
  release:
    uses: belgif/workflows/.github/workflows/dependabot-auto-merge-workflow.yml@main
    secrets: inherit
